// Pure Business Logic Verification Tests
import { authorize, hasPermission, hasScope } from '../auth/rbac';
import { AndonStatus, ProductionStatus, User } from '../../types';
export interface TestResult { suite:string; name:string; passed:boolean; actual?:unknown; expected?:unknown; error?:string; durationMs:number; }
export function calculateAchievement(actual:number,target:number):number { if(target<=0)return 0; return Math.round((actual/target)*1000)/10; }
export function calculateTaktTimeSec(operatingMinutes:number,targetQty:number):number { if(targetQty<=0)return 0; return Math.round((operatingMinutes*60)/targetQty); }
export function isValidLineStatusTransition(from:ProductionStatus,to:ProductionStatus):boolean { if(from===to)return true; if(from==='STOPPED'&&(to==='RUNNING'||to==='CHANGEOVER'))return true; if(from==='RUNNING'&&['WARNING','STOPPED','CHANGEOVER','IDLE'].includes(to))return true; if(from==='WARNING'&&['RUNNING','STOPPED','IDLE'].includes(to))return true; if(from==='CHANGEOVER'&&['RUNNING','IDLE','WARNING'].includes(to))return true; if(from==='IDLE'&&['CHANGEOVER','RUNNING'].includes(to))return true; return false; }
const ANDON_STEPS:AndonStatus[]=['NEW','ACKNOWLEDGED','ARRIVED','INVESTIGATING','COUNTERMEASURE','VERIFICATION','CLOSED'];
export function getNextAndonStatus(current:AndonStatus):AndonStatus|null { const idx=ANDON_STEPS.indexOf(current); return idx<0||idx===ANDON_STEPS.length-1?null:ANDON_STEPS[idx+1]; }
export function isValidAndonStep(from:AndonStatus,to:AndonStatus):boolean { const a=ANDON_STEPS.indexOf(from),b=ANDON_STEPS.indexOf(to); return a>=0&&b>=0&&b===a+1; }
export function evaluatePokaYokeRule(operator:'EQUALS'|'NOT_EQUALS'|'GREATER_THAN'|'LESS_THAN'|'IS_DUPLICATE',expectedValue:string,actualValue:unknown):{passed:boolean;message:string}{ switch(operator){case'EQUALS':{const p=String(actualValue)===expectedValue;return{passed:p,message:p?'Check Passed':`Expected '${expectedValue}' but got '${actualValue}'`};}case'NOT_EQUALS':{const p=String(actualValue)!==expectedValue;return{passed:p,message:p?'Check Passed':`Forbidden value '${actualValue}' detected`};}case'GREATER_THAN':{const p=Number(actualValue)>Number(expectedValue);return{passed:p,message:p?'Check Passed':`Value ${actualValue} below required minimum ${expectedValue}`};}case'LESS_THAN':{const p=Number(actualValue)<Number(expectedValue);return{passed:p,message:p?'Check Passed':`Value ${actualValue} exceeds allowable threshold ${expectedValue}`};}case'IS_DUPLICATE':{const d=actualValue==='BARCODE-DUPLICATE'||actualValue==='ALREADY_SCANNED';return{passed:!d,message:!d?'Unique Serial Verified':`Duplicate barcode detected: '${actualValue}'`};}} }
export function formatHandoverSummary(data:{shiftFrom:string;shiftTo:string;achievementPct:number;actualQty:number;targetQty:number;stopsCount:number;totalDowntimeMin:number;}):string{return`${data.shiftFrom} → ${data.shiftTo} | Achievement: ${data.achievementPct}% (${data.actualQty}/${data.targetQty}) | Stops: ${data.stopsCount} (${data.totalDowntimeMin}m)`;}
export function runFactoryOsBusinessLogicTests():TestResult[]{const results:TestResult[]=[];const run=(suite:string,name:string,fn:()=>void)=>{const t0=performance.now();try{fn();results.push({suite,name,passed:true,durationMs:Math.round((performance.now()-t0)*100)/100});}catch(err){results.push({suite,name,passed:false,error:err instanceof Error?err.message:String(err),durationMs:Math.round((performance.now()-t0)*100)/100});}};
 run('Production Metrics','achievement',()=>{if(calculateAchievement(588,640)!==91.9)throw Error('bad achievement');}); run('Production Metrics','takt',()=>{if(calculateTaktTimeSec(480,640)!==45)throw Error('bad takt');});
 run('RBAC','operator cannot edit target',()=>{if(hasPermission('OPERATOR','production:edit_target'))throw Error('privilege escalation');});
 run('RBAC','admin is not process authority',()=>{if(hasPermission('ADMIN','quality:verify_close')||hasPermission('ADMIN','maintenance:close_ticket')||hasPermission('ADMIN','andon:close'))throw Error('admin has operational authority');});
 const qa:User={id:'q',name:'QA',badgeNumber:'Q1',email:'q@local',role:'SUPERVISOR',department:'QUALITY',accessScope:{type:'LINE',lineIds:['line-01']},active:true};
 run('Authorization','quality supervisor can verify own-line defect',()=>{if(!authorize(qa,'quality:verify_close',{lineId:'line-01'}))throw Error('expected allow');});
 run('Authorization','quality supervisor cannot verify other-line defect',()=>{if(authorize(qa,'quality:verify_close',{lineId:'line-02'}))throw Error('scope bypass');});
 run('Authorization','line scope denies another line',()=>{if(hasScope({type:'LINE',lineIds:['line-01']},{lineId:'line-02'}))throw Error('scope bypass');});
 run('Andon Lifecycle','strict next step',()=>{if(getNextAndonStatus('NEW')!=='ACKNOWLEDGED'||isValidAndonStep('NEW','COUNTERMEASURE'))throw Error('andon skip allowed');});
 run('Andon Lifecycle','cannot close before verification',()=>{if(isValidAndonStep('COUNTERMEASURE','CLOSED'))throw Error('premature close allowed');});
 run('Poka-Yoke','duplicate barcode blocks',()=>{if(evaluatePokaYokeRule('IS_DUPLICATE','FALSE','BARCODE-DUPLICATE').passed)throw Error('duplicate passed');});
 return results;}
